baseURL = 'https://lonfas.org/'
locale = 'en-us'
# title = 'LonFas'
theme = 'blowfish'

[[menu.main]]
    name = "home"
    url = "/"
    weight = 10

[[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 20

[params]
